### PR TITLE
Add a row-spacer class and add a row element for login.html and home.…

### PR DESCRIPTION
**Pull request by YPCrumble**
…html files.

### CODE REVIEW

**Comment by YPCrumble** [comment]
@autn not sure this is the best way, but because `block content` in `index.html` is inside a `div.container` it makes sense that the first Bootstrap element is a `row`. This adds that row to two files and also adds a `row-spacer` class to add some padding above a row.

Let me know what you think or if you have a better way!

**Comment by autn** [comment]
@YPCrumble this looks good! Do you think we need to add to the other pages, or all pages (add to index.html)?

**Review by autn — APPROVED** [review]

**Comment by autn** [comment]
Also, what do you think about using Bootstrap spacing https://getbootstrap.com/docs/4.0/utilities/spacing/?

**Comment by YPCrumble** [comment]
@autn I wasn't aware of the bootstrap default spacing - that looks way better to me! Would you rework this to use that spacing instead of `row-spacer` like I did here?

Please do add to the other pages as well :D.

**Comment by autn** [comment]
@YPCrumble ok, I will update the PR

**Comment by autn** [comment]
@YPCrumble I updated the PR, please add your review :smile:

**Comment by YPCrumble** [comment]
@autn nice! I can't approve using the button because I initiated the PR, but feel free to merge this in!

**Pull request merged**
